### ISSUE TITLE
Expired OneDrive Link for Pre-generated LEMON Models

### ISSUE THREAD

**Issue by WLFJ** [ganler/nnsmith-asplos-artifact#1]
Hello @ganler ,

I hope this message finds you well. I am currently attempting to replicate a study from your published work and have encountered an issue with one of the resources.

Specifically, the OneDrive link provided for downloading the pre-generated LEMON models appears to be expired. I was wondering if there might be an alternative link or method to access these models?

Thank you for your time and for the valuable work you've shared with the community.

**Comment by ganler** [comment]
Hi please find the updated link here: https://uillinoisedu-my.sharepoint.com/:u:/g/personal/jiawei6_illinois_edu/EciCT0E4v0tJlyXHgnbDeeIBB0UzhYB01qBuy_b-GtY6IA?e=Mxh8XU
